import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Header
        'header.title': 'NLT-PR',
        'header.subtitle': 'Insight',
        'nav.dashboard': 'Dashboard',
        'nav.financials': 'Financial Analysis',
        'nav.compliance': 'Compliance Tracker',
        'nav.chat': 'Notebook Assistant',
        'nav.industry': 'Industry',
        'nav.act60': 'Act 60',
        'status.active': 'System Active',

        // Overview
        'overview.title': 'NLT-PR Financial Insight Dashboard',
        'overview.subtitle': 'AI-powered analysis connected to NotebookLM',
        'overview.documents': 'Documents Analyzed',
        'overview.compliance': 'Compliance Score',
        'overview.quickActions': 'Quick Actions',
        'overview.syncData': 'Sync Data',
        'overview.syncInventory': 'Sync Inventory',
        'overview.generateReport': 'Generate Report',
        'overview.recentActivity': 'Recent Activity',
        'overview.notebookConnection': 'Notebook Connection',
        'overview.connectedMCP': 'Connected via MCP',

        // Financial Analysis
        'financial.title': 'Financial Performance Overview',
        'financial.subtitle': 'Audited vs. Industry Benchmarks',
        'financial.lastSync': 'Last synced',
        'financial.notSynced': 'Not synced yet',
        'financial.syncNow': '↻ Sync Now',
        'financial.analyzing': 'Analyzing...',
        'financial.syncing': 'Syncing Financial Data...',
        'financial.complete': 'Complete',
        'financial.deepAnalysis': 'Running Deep Analysis...',
        'financial.yearly': 'Yearly',
        'financial.monthly': 'Monthly',
        'financial.revenue': 'Revenue',
        'financial.grossMargin': 'Gross Margin',
        'financial.target': 'Target',
        'financial.aiAnalysis': 'AI Analysis',
        'financial.analysisPending': 'Analysis pending...',
        'financial.marginVsIndustry': 'Margin vs Industry',
        'financial.noData': 'No segmented data found. Try syncing again.',
        'financial.clickSync': 'Click Sync Now to generate the report.',
        'financial.aiSummary': 'AI Financial Summary',
        'financial.narrativeNote': 'Note: Structured data (segments, KPIs) not available. Showing narrative response.',

        // Compliance Tracker
        'compliance.title': 'Compliance & Document Tracker',
        'compliance.subtitle': 'Real-time scan of PDF documents with content-based identification',
        'compliance.overallScore': 'Overall Compliance Score',
        'compliance.documentsReviewed': 'Documents Reviewed',
        'compliance.issuesFound': 'Issues Found',
        'compliance.lastAudit': 'Last Audit',
        'compliance.auditItems': 'Audit Items',
        'compliance.passed': 'Passed',
        'compliance.warning': 'Warning',
        'compliance.failed': 'Failed',
        'compliance.documentsFound': 'Documents Found',
        'compliance.missingDocuments': 'Missing Documents',
        'compliance.totalScanned': 'Total PDFs Scanned',
        'compliance.lastScan': 'Last scan',
        'compliance.detected': 'PDFs detected',
        'compliance.scanNow': '↻ Scan Now',
        'compliance.scanning': '⏳ Scanning...',
        'compliance.category': 'Document Category',
        'compliance.status': 'Status',
        'compliance.latestFile': 'Latest File',
        'compliance.lastModified': 'Last Modified',
        'compliance.noDocument': 'No document found',
        'compliance.allDocuments': 'All Detected Documents',
        'compliance.found': '✓ FOUND',
        'compliance.missing': '✕ MISSING',
        'compliance.loading': '⟳ LOADING',
        'compliance.documentPeriod': 'Document Period',
        // Document Categories
        'doc.financialStatements': 'Financial Statements',
        'doc.taxReturns': 'Tax Returns',
        'doc.municipalTaxes': 'Municipal Taxes (Patente)',
        'doc.propertyTax': 'Property Tax (CRIM)',
        'doc.depreciationSchedule': 'Depreciation Schedule',
        'doc.auditReports': 'Audit Reports',
        'doc.salesTaxReports': 'Sales Tax Reports',
        'doc.payrollReports': 'Payroll Reports',
        'doc.insuranceCertificates': 'Insurance Certificates',
        'doc.businessLicenses': 'Business Licenses',
        'doc.engagementLetter': 'Engagement Letter',
        'doc.representationLetter': 'Representation Letter',

        // Notebook Chat
        'chat.title': 'Notebook Assistant',
        'chat.subtitle': 'Ask questions about your NLT-PR financial documents',
        'chat.placeholder': 'Ask about financial data, compliance, trends...',
        'chat.send': 'Send',
        'chat.thinking': 'Thinking...',
        'chat.welcome': 'Welcome! I can help you analyze NLT-PR financial documents. What would you like to know?',

        // Financial Ratios Section
        'ratios.title': 'Financial Ratios from FS File',
        'ratios.source': 'Source',
        'ratios.asOf': 'As of',
        'ratios.solvency': 'Solvency Ratios',
        'ratios.safety': 'Safety Ratios',
        'ratios.profitability': 'Profitability Ratios',
        'ratios.assetManagement': 'Asset Management Ratios',
        'ratios.leadingIndicators': 'Leading Financial Indicators',
        'ratios.ratio': 'Ratio',
        'ratios.indicator': 'Indicator',
        'ratios.current': 'Current',
        'ratios.prior': 'Prior',
        'ratios.benchmark': 'Benchmark',
        'ratios.currentValue': 'Current Value',
        'ratios.priorYear': 'Prior Year',
        'ratios.industryBenchmark': 'Industry Benchmark',
        'ratios.whatMeans': 'What This Ratio Means',
        'ratios.recommendations': 'Recommendations to Improve',
        'ratios.perspectives': 'Stakeholder Perspectives',
        'ratios.fiscalView': 'Fiscal / Tax Authority View',
        'ratios.bankView': 'Bank / Lender View',
        'ratios.manufacturerView': 'Manufacturer / Supplier View',
        'ratios.investorView': 'Investor / Buyer View',
        'ratios.close': 'Close',
        'ratios.formula': 'Formula',
        'ratios.days': 'days',

        // Status Badges
        'status.above': '▲ Above',
        'status.below': '▼ Below',
        'status.atTarget': '● At Target',

        // Industry KPIs Matrix
        'kpi.title': 'Industrial KPI Matrix (Heavy Equipment & Forklift)',
        'kpi.sourceTitle': 'Source: Industry Log (Jan 2026)',
        'kpi.sourceDescription': 'Based on "Accounting for Equipment Rental and Sales" [Source 458] and "Comprehensive Strategic Report" [Source 714]. Operational efficiency is the true differentiator, not just volume.',
        'kpi.header': 'KPI (Indicator)',
        'kpi.bestInClass': 'Best in Class Standard',
        'kpi.actualResult': 'Actual Result (Dec 2024)',
        'kpi.statusAnalysis': 'Status / Analysis',
        'kpi.dollarUtilization': 'Dollar Utilization',
        'kpi.dollarUtilDesc': 'Critical to cover high costs in PR. If low, equipment is too expensive or rent is too cheap.',
        'kpi.timeUtilization': 'Time Utilization',
        'kpi.timeUtilDesc': '>85% means missed opportunities; <60% means excess fleet.',
        'kpi.absorptionRate': 'Absorption Rate',
        'kpi.absorptionDesc': 'Indicates coverage of fixed costs by services/parts.',
        'kpi.ebitdaMargin': 'EBITDA Margin',
        'kpi.ebitdaDesc': '⚠️ Alert: Signal of inefficiency or high maintenance costs.',
        'kpi.dso': 'Days Sales Outstanding (DSO)',
        'kpi.dsoDesc': '✅ Excellent. Superior to global competitors.',
        'kpi.inventoryTurnover': 'Inventory Turnover',
        'kpi.inventoryDesc': 'Slow. Inventory held for almost 5 months.',
        'kpi.notReported': 'Not reported',
        'kpi.estimated': 'Estimated',
        'kpi.days': 'Days',
        'kpi.times': 'times',
        'kpi.balancePoint': 'Balance point',
        'kpi.theHolyGrail': 'The Holy Grail',
        'kpi.masterFormulas': 'Master Formulas 2026',
        'kpi.financialUtilization': 'Financial Utilization',
        'kpi.financialUtilFormula': 'Annual Rental Revenue / Acquisition Cost (OEC)',
        'kpi.goal': 'Goal',
        'kpi.hardDown': 'Hard Down Status',
        'kpi.hardDownFormula': 'Units in Repair > 2 weeks / Total Fleet',
        'kpi.rule': 'Rule',
        'kpi.maxDays': 'Max 14 days',

        // Industry Analysis
        'industry.title': 'Industry Analysis',
        'industry.subtitle': 'NAICS Classification & Market Overview',
        'industry.naicsTitle': 'Commercial and Industrial Machinery and Equipment Rental',
        'industry.naicsSubtitle': 'Fork Lifts - Renting',
        'industry.sector': 'Real Estate and Rental and Leasing',
        'industry.description': 'Establishments primarily engaged in renting or leasing commercial-type and industrial-type machinery and equipment, including material handling machinery, industrial trucks, and forklifts.',
        'industry.globalMarket': 'Global Forklift Rental Market',
        'industry.materialHandling': 'Material Handling Equipment Rental',
        'industry.prManufacturing': 'PR Manufacturing Share of GDP',
        'industry.challengesTitle': 'Current Challenges',
        'industry.opportunitiesTitle': 'Growth Opportunities',
        'industry.challenge1Title': 'Energy Infrastructure',
        'industry.challenge1Desc': "Puerto Rico's fragile power grid and PREPA bankruptcy create operational uncertainty and higher costs.",
        'industry.challenge2Title': 'Electrification Mandates',
        'industry.challenge2Desc': 'CARB 2026 regulations phasing out propane/gas forklifts signal nationwide trend toward electric equipment.',
        'industry.challenge3Title': 'OSHA 2025 Compliance',
        'industry.challenge3Desc': 'Stricter documentation for equipment modifications, enhanced training records, and digital reporting requirements.',
        'industry.challenge4Title': 'Climate Resilience',
        'industry.challenge4Desc': 'Hurricane exposure requires robust contingency planning and equipment protection strategies.',
        'industry.opp1Title': 'Act 60 Tax Incentives',
        'industry.opp1Desc': '4% fixed income tax rate and 75% property tax exemption available for qualifying businesses.',
        'industry.opp2Title': '$2.2B New Investments',
        'industry.opp2Desc': 'Major pharmaceutical and manufacturing investments announced, creating demand for equipment rental.',
        'industry.opp3Title': 'Electric Fleet Transition',
        'industry.opp3Desc': 'First-mover advantage in lithium-ion forklift rental as industry transitions from propane.',
        'industry.opp4Title': 'Service Differentiation',
        'industry.opp4Desc': 'Bundled maintenance, training, and compliance services create competitive advantage.',
        'industry.legislationTitle': 'Regulatory & Legislative Updates',
        'industry.jurisdiction': 'Jurisdiction',
        'industry.lawRegulation': 'Law/Regulation',
        'industry.status': 'Status',
        'industry.impactRelevance': 'Impact & Relevance',
        'industry.statusActive': 'Active',
        'industry.statusPending': 'Effective 2026',
        'industry.oshaImpact': 'Stricter equipment modification documentation and enhanced training records required for 2025.',
        'industry.carbImpact': 'Phase-out of propane/gas forklifts starting Jan 2026. Signals likely federal trend.',
        'industry.act60Impact': '4% income tax, 75% property tax exemption for qualifying manufacturing businesses.',
        'industry.recommendationsTitle': 'Strategic Recommendations',
        'industry.rec1Title': 'Evaluate Act 60 Restructuring',
        'industry.rec1Desc': 'Consult with tax advisors to determine eligibility for Act 60 manufacturing incentives and potential tax savings.',
        'industry.rec2Title': 'Develop Electric Fleet Strategy',
        'industry.rec2Desc': 'Begin transitioning rental fleet to electric forklifts to prepare for regulatory changes and market demands.',
        'industry.rec3Title': 'Strengthen Training Programs',
        'industry.rec3Desc': 'Enhance operator certification and OSHA compliance tracking to meet 2025 enhanced documentation requirements.',
        'industry.rec4Title': 'Pursue Manufacturer Partnerships',
        'industry.rec4Desc': 'Establish stronger relationships with Toyota, Hyster, and electric equipment manufacturers for preferential terms.',

        // Act 60 Tab
        'act60.title': 'Act 60 Restructuring Analysis',
        'act60.subtitle': 'Puerto Rico Incentives Code - Manufacturing Tax Benefits',
        'act60.corpType': 'C-Corporation (Puerto Rico)',
        'act60.act60Entity': 'Act 60 Eligible Entity',
        'act60.years': 'years',
        'act60.months': 'months',
        'act60.incomeTax': 'Income Tax',
        'act60.propertyTax': 'Property Tax',
        'act60.municipalTax': 'Municipal Tax',
        'act60.distributionTax': 'Distribution Tax',
        'act60.currentStructure': 'Current Structure',
        'act60.proposedStructure': 'Proposed Structure',
        'act60.termDuration': 'Term',
        'act60.taxComparison': 'Tax Rate Comparison',
        'act60.current': 'Current',
        'act60.proposed': 'Act 60',
        'act60.keyBenefits': 'Key Benefits of Act 60',
        'act60.potentialSavings': 'POTENTIAL ANNUAL SAVINGS',
        'act60.benefit1Title': '4% Fixed Income Tax',
        'act60.benefit1Desc': 'vs standard 37.5% corporate rate. Applies to industrial development income.',
        'act60.benefit2Title': '75% Property Tax Exemption',
        'act60.benefit2Desc': 'Reduced property tax burden on real and personal property.',
        'act60.benefit3Title': '50% Municipal Tax Exemption',
        'act60.benefit3Desc': 'Reduced municipal license tax (patente) for eligible businesses.',
        'act60.benefit4Title': '0% Distribution Tax',
        'act60.benefit4Desc': 'No tax on dividend distributions to shareholders.',
        'act60.benefit5Title': '15-30 Year Terms',
        'act60.benefit5Desc': 'Initial 15-year decree with option to extend for additional 15 years.',
        'act60.benefit6Title': 'IVU Exemptions',
        'act60.benefit6Desc': 'Sales tax exemption on raw materials, machinery, and equipment.',
        'act60.estimatedSavings': 'Estimated Tax Savings',
        'act60.currentTax': 'Current Tax',
        'act60.act60Tax': 'Act 60 Tax',
        'act60.currentAnnualTax': 'Current Annual Tax (37.5%)',
        'act60.act60AnnualTax': 'Act 60 Annual Tax (4%)',
        'act60.savingsOver15Years': '15-Year Cumulative Savings',
        'act60.implementationRoadmap': 'Implementation Roadmap',
        'act60.phase1Title': 'Eligibility Assessment',
        'act60.phase1Task1': 'Review current corporate structure',
        'act60.phase1Task2': 'Verify manufacturing activity qualifies',
        'act60.phase1Task3': 'Consult with Act 60 tax specialist',
        'act60.phase1Task4': 'Prepare cost-benefit analysis',
        'act60.phase2Title': 'Application & Approval',
        'act60.phase2Task1': 'Prepare Act 60 application package',
        'act60.phase2Task2': 'Submit to DDEC (Dept. of Economic Development)',
        'act60.phase2Task3': 'Negotiate decree terms',
        'act60.phase2Task4': 'Obtain tax exemption decree',
        'act60.phase3Title': 'Corporate Restructuring',
        'act60.phase3Task1': 'Restructure entity if needed',
        'act60.phase3Task2': 'Update accounting systems',
        'act60.phase3Task3': 'Register for exempt status',
        'act60.phase3Task4': 'Notify stakeholders and lenders',
        'act60.phase4Title': 'Compliance & Reporting',
        'act60.phase4Task1': 'Annual compliance reporting',
        'act60.phase4Task2': 'Maintain employment requirements',
        'act60.phase4Task3': 'Track eligible income separately',
        'act60.phase4Task4': 'Periodic decree review/renewal',
        'act60.ongoing': 'Ongoing',
        'act60.disclaimer': 'Important',
        'act60.disclaimerText': 'This analysis is for informational purposes. Consult with qualified tax and legal professionals before making restructuring decisions.',

        // Misc
        'misc.more': 'more',
    },
    es: {
        // Header
        'header.title': 'NLT-PR',
        'header.subtitle': 'Insight',
        'nav.dashboard': 'Panel',
        'nav.financials': 'Análisis Financiero',
        'nav.compliance': 'Cumplimiento',
        'nav.chat': 'Asistente IA',
        'nav.industry': 'Industria',
        'nav.act60': 'Ley 60',
        'status.active': 'Sistema Activo',

        // Overview
        'overview.title': 'Panel de Análisis Financiero NLT-PR',
        'overview.subtitle': 'Análisis impulsado por IA conectado a NotebookLM',
        'overview.documents': 'Documentos Analizados',
        'overview.compliance': 'Puntuación de Cumplimiento',
        'overview.quickActions': 'Acciones Rápidas',
        'overview.syncData': 'Sincronizar Datos',
        'overview.syncInventory': 'Sincronizar Inventario',
        'overview.generateReport': 'Generar Reporte',
        'overview.recentActivity': 'Actividad Reciente',
        'overview.notebookConnection': 'Conexión a Notebook',
        'overview.connectedMCP': 'Conectado vía MCP',

        // Financial Analysis
        'financial.title': 'Resumen del Rendimiento Financiero',
        'financial.subtitle': 'Auditado vs. Puntos de Referencia de la Industria',
        'financial.lastSync': 'Última sincronización',
        'financial.notSynced': 'Sin sincronizar',
        'financial.syncNow': '↻ Sincronizar',
        'financial.analyzing': 'Analizando...',
        'financial.syncing': 'Sincronizando Datos Financieros...',
        'financial.complete': 'Completado',
        'financial.deepAnalysis': 'Ejecutando Análisis Profundo...',
        'financial.yearly': 'Anual',
        'financial.monthly': 'Mensual',
        'financial.revenue': 'Ingresos',
        'financial.grossMargin': 'Margen Bruto',
        'financial.target': 'Meta',
        'financial.aiAnalysis': 'Análisis IA',
        'financial.analysisPending': 'Análisis pendiente...',
        'financial.marginVsIndustry': 'Margen vs Industria',
        'financial.noData': 'No se encontraron datos segmentados. Intente sincronizar nuevamente.',
        'financial.clickSync': 'Haga clic en Sincronizar para generar el reporte.',
        'financial.aiSummary': 'Resumen Financiero IA',
        'financial.narrativeNote': 'Nota: Datos estructurados no disponibles. Mostrando respuesta narrativa.',

        // Compliance Tracker
        'compliance.title': 'Rastreador de Cumplimiento y Documentos',
        'compliance.subtitle': 'Escaneo en tiempo real de documentos PDF con identificación basada en contenido',
        'compliance.overallScore': 'Puntuación General de Cumplimiento',
        'compliance.documentsReviewed': 'Documentos Revisados',
        'compliance.issuesFound': 'Problemas Encontrados',
        'compliance.lastAudit': 'Última Auditoría',
        'compliance.auditItems': 'Elementos de Auditoría',
        'compliance.passed': 'Aprobado',
        'compliance.warning': 'Advertencia',
        'compliance.failed': 'Fallido',
        'compliance.documentsFound': 'Documentos Encontrados',
        'compliance.missingDocuments': 'Documentos Faltantes',
        'compliance.totalScanned': 'PDFs Escaneados',
        'compliance.lastScan': 'Último escaneo',
        'compliance.detected': 'PDFs detectados',
        'compliance.scanNow': '↻ Escanear',
        'compliance.scanning': '⏳ Escaneando...',
        'compliance.category': 'Categoría de Documento',
        'compliance.status': 'Estado',
        'compliance.latestFile': 'Archivo Más Reciente',
        'compliance.lastModified': 'Última Modificación',
        'compliance.noDocument': 'Documento no encontrado',
        'compliance.allDocuments': 'Todos los Documentos Detectados',
        'compliance.found': '✓ ENCONTRADO',
        'compliance.missing': '✕ FALTANTE',
        'compliance.loading': '⟳ CARGANDO',
        'compliance.documentPeriod': 'Período del Documento',
        // Document Categories
        'doc.financialStatements': 'Estados Financieros',
        'doc.taxReturns': 'Planillas Contributivas',
        'doc.municipalTaxes': 'Patente Municipal',
        'doc.propertyTax': 'Contribución Inmueble (CRIM)',
        'doc.depreciationSchedule': 'Anejo de Depreciación',
        'doc.auditReports': 'Informes de Auditoría',
        'doc.salesTaxReports': 'Informes IVU',
        'doc.payrollReports': 'Informes de Nómina',
        'doc.insuranceCertificates': 'Certificados de Seguro',
        'doc.businessLicenses': 'Licencias Comerciales',
        'doc.engagementLetter': 'Carta de Compromiso',
        'doc.representationLetter': 'Carta de Representación',

        // Notebook Chat
        'chat.title': 'Asistente de Notebook',
        'chat.subtitle': 'Haga preguntas sobre sus documentos financieros de NLT-PR',
        'chat.placeholder': 'Pregunte sobre datos financieros, cumplimiento, tendencias...',
        'chat.send': 'Enviar',
        'chat.thinking': 'Pensando...',
        'chat.welcome': '¡Bienvenido! Puedo ayudarle a analizar los documentos financieros de NLT-PR. ¿Qué desea saber?',

        // Financial Ratios Section
        'ratios.title': 'Razones Financieras del Archivo FS',
        'ratios.source': 'Fuente',
        'ratios.asOf': 'Al',
        'ratios.solvency': 'Razones de Solvencia',
        'ratios.safety': 'Razones de Seguridad',
        'ratios.profitability': 'Razones de Rentabilidad',
        'ratios.assetManagement': 'Razones de Gestión de Activos',
        'ratios.leadingIndicators': 'Indicadores Financieros Anticipados',
        'ratios.ratio': 'Razón',
        'ratios.indicator': 'Indicador',
        'ratios.current': 'Actual',
        'ratios.prior': 'Anterior',
        'ratios.benchmark': 'Referencia',
        'ratios.currentValue': 'Valor Actual',
        'ratios.priorYear': 'Año Anterior',
        'ratios.industryBenchmark': 'Referencia de la Industria',
        'ratios.whatMeans': 'Qué Significa Esta Razón',
        'ratios.recommendations': 'Recomendaciones para Mejorar',
        'ratios.perspectives': 'Perspectivas de las Partes Interesadas',
        'ratios.fiscalView': 'Vista del Fisco / Autoridad Tributaria',
        'ratios.bankView': 'Vista del Banco / Prestamista',
        'ratios.manufacturerView': 'Vista del Fabricante / Proveedor',
        'ratios.investorView': 'Vista del Inversor / Comprador',
        'ratios.close': 'Cerrar',
        'ratios.formula': 'Fórmula',
        'ratios.days': 'días',

        // Status Badges
        'status.above': '▲ Superior',
        'status.below': '▼ Inferior',
        'status.atTarget': '● En Meta',

        // Industry KPIs Matrix
        'kpi.title': 'Matriz de KPIs Industriales (Heavy Equipment & Forklift)',
        'kpi.sourceTitle': 'Fuente: La Bitácora de la Industria (Ene 2026)',
        'kpi.sourceDescription': 'Basado en "Contabilidad para Alquiler y Venta de Maquinaria" [Fuente 458] y "Informe Estratégico Integral" [Fuente 714]. La eficiencia operativa es el verdadero diferencial, no solo el volumen.',
        'kpi.header': 'KPI (Indicador)',
        'kpi.bestInClass': 'Estándar "Best in Class"',
        'kpi.actualResult': 'Resultado Real (Dic 2024)',
        'kpi.statusAnalysis': 'Estado / Análisis',
        'kpi.dollarUtilization': 'Utilización Financiera (Dollar Utilization)',
        'kpi.dollarUtilDesc': 'Crítico para cubrir costos altos en PR. Si es bajo, el equipo es muy caro o la renta muy barata.',
        'kpi.timeUtilization': 'Utilización Física (Time Utilization)',
        'kpi.timeUtilDesc': '>85% implica pérdida de oportunidades; <60% exceso de flota.',
        'kpi.absorptionRate': 'Tasa de Absorción (Absorption Rate)',
        'kpi.absorptionDesc': 'Indica cobertura de gastos fijos por servicios/piezas.',
        'kpi.ebitdaMargin': 'Margen EBITDA',
        'kpi.ebitdaDesc': '⚠️ Alerta: Señal de ineficiencia o altos costos de mantenimiento.',
        'kpi.dso': 'Días de Cobro (DSO)',
        'kpi.dsoDesc': '✅ Excelente. Superior a competidores globales.',
        'kpi.inventoryTurnover': 'Rotación de Inventario',
        'kpi.inventoryDesc': 'Lento. Inventario retenido por casi 5 meses.',
        'kpi.notReported': 'No reportado',
        'kpi.estimated': 'Estimado',
        'kpi.days': 'Días',
        'kpi.times': 'veces',
        'kpi.balancePoint': 'Punto de equilibrio',
        'kpi.theHolyGrail': 'El Santo Grial',
        'kpi.masterFormulas': 'Fórmulas Maestras 2026',
        'kpi.financialUtilization': 'Utilización Financiera',
        'kpi.financialUtilFormula': 'Ingresos Renta Anual / Costo Adquisición (OEC)',
        'kpi.goal': 'Meta',
        'kpi.hardDown': 'Estado "Hard Down"',
        'kpi.hardDownFormula': 'Unidades Reparación > 2 sem / Total Flota',
        'kpi.rule': 'Regla',
        'kpi.maxDays': 'Max 14 días',

        // Industry Analysis
        'industry.title': 'Análisis de Industria',
        'industry.subtitle': 'Clasificación NAICS y Panorama del Mercado',
        'industry.naicsTitle': 'Alquiler de Maquinaria y Equipo Comercial e Industrial',
        'industry.naicsSubtitle': 'Montacargas - Alquiler',
        'industry.sector': 'Bienes Raíces y Arrendamiento',
        'industry.description': 'Establecimientos dedicados principalmente al alquiler de maquinaria y equipo comercial e industrial, incluyendo maquinaria de manejo de materiales, camiones industriales y montacargas.',
        'industry.globalMarket': 'Mercado Global de Alquiler de Montacargas',
        'industry.materialHandling': 'Alquiler de Equipo de Manejo de Materiales',
        'industry.prManufacturing': 'Participación Manufactura PR en PIB',
        'industry.challengesTitle': 'Retos Actuales',
        'industry.opportunitiesTitle': 'Oportunidades de Crecimiento',
        'industry.challenge1Title': 'Infraestructura Energética',
        'industry.challenge1Desc': 'La frágil red eléctrica de Puerto Rico y la quiebra de PREPA crean incertidumbre operacional y costos más altos.',
        'industry.challenge2Title': 'Mandatos de Electrificación',
        'industry.challenge2Desc': 'Regulaciones CARB 2026 eliminando montacargas de propano/gas señalan tendencia nacional hacia equipos eléctricos.',
        'industry.challenge3Title': 'Cumplimiento OSHA 2025',
        'industry.challenge3Desc': 'Documentación más estricta para modificaciones de equipo, registros de entrenamiento mejorados y requisitos de informes digitales.',
        'industry.challenge4Title': 'Resiliencia Climática',
        'industry.challenge4Desc': 'La exposición a huracanes requiere planificación de contingencia robusta y estrategias de protección de equipos.',
        'industry.opp1Title': 'Incentivos Ley 60',
        'industry.opp1Desc': 'Tasa fija de 4% de impuesto sobre ingresos y 75% de exención de contribución sobre la propiedad disponible.',
        'industry.opp2Title': '$2.2B en Nuevas Inversiones',
        'industry.opp2Desc': 'Inversiones importantes en farmacéuticas y manufactura anunciadas, creando demanda de alquiler de equipos.',
        'industry.opp3Title': 'Transición a Flota Eléctrica',
        'industry.opp3Desc': 'Ventaja de pionero en alquiler de montacargas de litio-ion mientras la industria transiciona del propano.',
        'industry.opp4Title': 'Diferenciación de Servicios',
        'industry.opp4Desc': 'Servicios integrados de mantenimiento, entrenamiento y cumplimiento crean ventaja competitiva.',
        'industry.legislationTitle': 'Actualizaciones Regulatorias y Legislativas',
        'industry.jurisdiction': 'Jurisdicción',
        'industry.lawRegulation': 'Ley/Regulación',
        'industry.status': 'Estado',
        'industry.impactRelevance': 'Impacto y Relevancia',
        'industry.statusActive': 'Activo',
        'industry.statusPending': 'Efectivo 2026',
        'industry.oshaImpact': 'Documentación de modificaciones de equipo más estricta y registros de entrenamiento mejorados requeridos para 2025.',
        'industry.carbImpact': 'Eliminación de montacargas de propano/gas a partir de enero 2026. Señala probable tendencia federal.',
        'industry.act60Impact': '4% impuesto sobre ingresos, 75% exención de contribución sobre la propiedad para negocios de manufactura cualificados.',
        'industry.recommendationsTitle': 'Recomendaciones Estratégicas',
        'industry.rec1Title': 'Evaluar Reestructuración Ley 60',
        'industry.rec1Desc': 'Consultar con asesores contributivos para determinar elegibilidad para incentivos de manufactura Ley 60 y ahorros potenciales.',
        'industry.rec2Title': 'Desarrollar Estrategia de Flota Eléctrica',
        'industry.rec2Desc': 'Comenzar transición de flota de alquiler a montacargas eléctricos para prepararse para cambios regulatorios y demandas del mercado.',
        'industry.rec3Title': 'Fortalecer Programas de Entrenamiento',
        'industry.rec3Desc': 'Mejorar certificación de operadores y seguimiento de cumplimiento OSHA para cumplir con requisitos de documentación mejorada 2025.',
        'industry.rec4Title': 'Buscar Alianzas con Fabricantes',
        'industry.rec4Desc': 'Establecer relaciones más fuertes con Toyota, Hyster y fabricantes de equipos eléctricos para términos preferenciales.',

        // Act 60 Tab
        'act60.title': 'Análisis de Reestructuración Ley 60',
        'act60.subtitle': 'Código de Incentivos de Puerto Rico - Beneficios Contributivos de Manufactura',
        'act60.corpType': 'Corporación C (Puerto Rico)',
        'act60.act60Entity': 'Entidad Elegible Ley 60',
        'act60.years': 'años',
        'act60.months': 'meses',
        'act60.incomeTax': 'Contribución sobre Ingresos',
        'act60.propertyTax': 'Contribución sobre Propiedad',
        'act60.municipalTax': 'Patente Municipal',
        'act60.distributionTax': 'Contribución sobre Distribuciones',
        'act60.currentStructure': 'Estructura Actual',
        'act60.proposedStructure': 'Estructura Propuesta',
        'act60.termDuration': 'Término',
        'act60.taxComparison': 'Comparación de Tasas Contributivas',
        'act60.current': 'Actual',
        'act60.proposed': 'Ley 60',
        'act60.keyBenefits': 'Beneficios Clave de la Ley 60',
        'act60.potentialSavings': 'AHORROS ANUALES POTENCIALES',
        'act60.benefit1Title': '4% Contribución Fija sobre Ingresos',
        'act60.benefit1Desc': 'vs tasa corporativa estándar de 37.5%. Aplica a ingresos de desarrollo industrial.',
        'act60.benefit2Title': '75% Exención Contribución Propiedad',
        'act60.benefit2Desc': 'Reducción de carga contributiva sobre propiedad mueble e inmueble.',
        'act60.benefit3Title': '50% Exención Patente Municipal',
        'act60.benefit3Desc': 'Reducción de patente municipal para negocios elegibles.',
        'act60.benefit4Title': '0% Contribución sobre Distribuciones',
        'act60.benefit4Desc': 'Sin contribución sobre distribuciones de dividendos a accionistas.',
        'act60.benefit5Title': 'Términos de 15-30 Años',
        'act60.benefit5Desc': 'Decreto inicial de 15 años con opción de extender por 15 años adicionales.',
        'act60.benefit6Title': 'Exenciones de IVU',
        'act60.benefit6Desc': 'Exención de impuesto sobre ventas en materias primas, maquinaria y equipo.',
        'act60.estimatedSavings': 'Ahorros Contributivos Estimados',
        'act60.currentTax': 'Contribución Actual',
        'act60.act60Tax': 'Contribución Ley 60',
        'act60.currentAnnualTax': 'Contribución Anual Actual (37.5%)',
        'act60.act60AnnualTax': 'Contribución Anual Ley 60 (4%)',
        'act60.savingsOver15Years': 'Ahorros Acumulados 15 Años',
        'act60.implementationRoadmap': 'Hoja de Ruta de Implementación',
        'act60.phase1Title': 'Evaluación de Elegibilidad',
        'act60.phase1Task1': 'Revisar estructura corporativa actual',
        'act60.phase1Task2': 'Verificar que actividad de manufactura cualifica',
        'act60.phase1Task3': 'Consultar con especialista en Ley 60',
        'act60.phase1Task4': 'Preparar análisis de costo-beneficio',
        'act60.phase2Title': 'Solicitud y Aprobación',
        'act60.phase2Task1': 'Preparar paquete de solicitud Ley 60',
        'act60.phase2Task2': 'Someter a DDEC (Depto. Desarrollo Económico)',
        'act60.phase2Task3': 'Negociar términos del decreto',
        'act60.phase2Task4': 'Obtener decreto de exención contributiva',
        'act60.phase3Title': 'Reestructuración Corporativa',
        'act60.phase3Task1': 'Reestructurar entidad si es necesario',
        'act60.phase3Task2': 'Actualizar sistemas de contabilidad',
        'act60.phase3Task3': 'Registrar para estatus exento',
        'act60.phase3Task4': 'Notificar a partes interesadas y prestamistas',
        'act60.phase4Title': 'Cumplimiento e Informes',
        'act60.phase4Task1': 'Informes anuales de cumplimiento',
        'act60.phase4Task2': 'Mantener requisitos de empleo',
        'act60.phase4Task3': 'Rastrear ingresos elegibles por separado',
        'act60.phase4Task4': 'Revisión/renovación periódica del decreto',
        'act60.ongoing': 'Continuo',
        'act60.disclaimer': 'Importante',
        'act60.disclaimerText': 'Este análisis es solo para propósitos informativos. Consulte con profesionales contributivos y legales cualificados antes de tomar decisiones de reestructuración.',

        // Misc
        'misc.more': 'más',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>(() => {
        const saved = localStorage.getItem('nlt-language');
        return (saved as Language) || 'en';
    });

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('nlt-language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
